version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.6.0
    ports:
      - "4444:4444"
    networks:
      - e2e
  chrome:
    image: selenium/node-chrome:3.6.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
      - wp-e2e-tests-data-volume:/wp-e2e-tests:ro
    networks:
      - e2e
networks:
  e2e:
volumes:
  wp-e2e-tests-data-volume:
    external: true
